assetDir = "static"
baseurl = "/"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
enableRobotsTXT = true
googleAnalytics = "UA-123723601-1"
languageCode = "en-us"
languageLang = "en"
title = "Lake Martin Chiro"
[imaging]
quality = 90
[[menu.main]]
name = "What To Expect"
url = "/what-to-expect"
weight = 5
[[menu.main]]
name = "Our Services"
url = "/our-services/"
weight = 4
[[menu.main]]
name = "Care Team"
url = "/your-care-team/"
weight = 3
[[menu.main]]
name = "Dr. Peaden"
url = "/dr-peaden/"
weight = 2
[params]
description = "At Lake Martin Chiropractic we know that patient relationships are important. Our staff always puts the needs and wellbeing of our patients first."
email = "lakemartinchiro@gmail.com"
facebook = "https://www.facebook.com/Lake-Martin-Chiropractic-Health-Center-126017201362305/"
instagram = "https://www.instagram.com/lakemartinchiropractic/"
